### ISSUE TITLE
Composer issues

### ISSUE THREAD

**Issue by sjaakp** [madand/yii2-underscore#1]
Your requirements could not be resolved to an installable set of packages.
- madand/yii2-underscore 1.8 requires bower-asset/underscore 1.8.\* -> no matching package found.

... and then the same for 1.7, 1.6, and 1.5.

**Comment by madand** [comment]
@sjaakp please ensure that you have `composer-asset-plugin` plugin installed:

``` bash
php composer.phar global require "fxp/composer-asset-plugin:~1.0.0"
```

Since that plugin is required for composer-based installation of the Yii2 itself, I treat it like an implicit dependency and thus no mention in readme.

**Comment by sjaakp** [comment]
O yes, it is installed. I successfully installed lots of Yii2 extensions with bower-assets.

---

Sjaak Priester

 mailto:sjaak@sjaakpriester.nl sjaak@sjaakpriester.nl

Van: MadAnd [mailto:notifications@github.com] 
Verzonden: dinsdag 30 juni 2015 14:35
Aan: MadAnd/yii2-underscore
CC: Sjaak Priester
Onderwerp: Re: [yii2-underscore] Composer issues (#1)

@sjaakp https://github.com/sjaakp  please ensure that you have composer-asset-plugin plugin installed:

php composer.phar global require "fxp/composer-asset-plugin:~1.0.0"

Since that plugin is required for composer-based installation of the Yii2 itself, I treat it like an implicit dependency and thus no mention in readme.

**Comment by madand** [comment]
Just tried to create test app with `yii2-app-basic` and install `yii2-underscore` - all is OK.
Well, you might try the following:
- run `php composer.phar clear-cache`
- delete all contents of the `vendor/` directory in you project and run `php composer.phar update`

**Comment by sjaakp** [comment]
That did it. Thanks.

---

Sjaak Priester

 mailto:sjaak@sjaakpriester.nl sjaak@sjaakpriester.nl

Van: MadAnd [mailto:notifications@github.com] 
Verzonden: dinsdag 30 juni 2015 14:52
Aan: MadAnd/yii2-underscore
CC: Sjaak Priester
Onderwerp: Re: [yii2-underscore] Composer issues (#1)

Just tried to create test app with yii2-app-basic and install yii2-underscore - all is OK.
Well, you might try the following:
-   run php composer.phar clear-cache 
-   delete all contents of the vendor/ directory in you project and run php composer.phar update

**Comment by madand** [comment]
You're welcome. It's like first things to try whenever Composer throws some strange errors.
